### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by sergi0g** [JonasHiltl/openchangelog#2]
The demo page linked from the footer of the homepage (demo.openchangelog.com) returns a 404

![Screenshot_20240830_210837.jpg](https://github.com/user-attachments/assets/27712e18-152c-4c27-9776-16f4d401eee5)

**Comment by JonasHiltl** [comment]
@sergi0g thanks for bringing this to my attention. Yesterday I changed the subdomain for a demo but never changed it back to demo.openchangelog.com. Should be fixed now
