### ISSUE TITLE
[Docs] Add contribution guide

### ISSUE THREAD

**Issue by sergi0g** [JonasHiltl/openchangelog#6]
Instructions on how to contribute and set up a development environment are crucial to attract more developers on a project.

This can either be a section in the README or a `CONTRIBUTING.MD` at the root of the repository.

I'm not sure if I did it correctly, but the only thing that worked for me was downloading `air`, `templ` and `tailwindcss`.

The docs should include having to run `templ generate`, etc. They could also include additional steps before submitting a PR, like formatting the code.

**Comment by JonasHiltl** [comment]
Hi @sergi0g, I'v opened PR #10 to add a `CONTRIBUTING.md` file. Please have a look and let me know if you think anything is missing or could be improved. Thanks!

**Comment by sergi0g** [comment]
@JonasHiltl I left some comments!

**Comment by JonasHiltl** [comment]
@sergi0g I can't see any comments on the PR. I changed it from a draft to open PR, maybe now you can leave a review

**Comment by sergi0g** [comment]
@JonasHiltl sorry, I don't know how to use github reviews on mobile yet... You should be able to see them now

**Comment by JonasHiltl** [comment]
@sergi0g Thanks for taking the time and reviewing the PR. Feel free to open issues if you encounter any problems with Openchangelog.
